### ISSUE TITLE
How to change the moving parameters in the code

### ISSUE THREAD

**Issue by zyatom** [Kvicksilver/pyWinKeys#1]
The parameters of the move are not fixed in the code

**Comment by Crypthid** [comment]
Uncertain what it's that you are asking for. 
To perform absolute moves in screen coordinates (pixel x, pixel y) you use function mouse_move with parameter relative=False
To perform moves based on your current mouse position (pixel dx, pixel dy) you use function mouse_move with parameter relative=True.

If you wanted to change the resolution of the move operation you could modify _SCREEN_X_MULTIPLIER, _SCREEN_Y_MULTIPLIER which are decided based on the resolution of the screen in function refresh_monitor_size.
